In [1]:
import numpy as np

In [7]:
np.__version__

'1.26.4'

In [8]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [9]:
type(my_list)

list

In [10]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
type(my_list)

list

In [12]:
print(type(arr))

<class 'numpy.ndarray'>


In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(10,20,4)

array([10, 14, 18])

In [16]:
np.arange(20,10)

array([], dtype=int32)

In [17]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros(5,dtype=int) #hyperparameter

array([0, 0, 0, 0, 0])

In [20]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.zeros((5,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
rand(3,2)

NameError: name 'rand' is not defined

In [24]:
np.random.rand(3,2)

array([[0.33303761, 0.6738438 ],
       [0.77706249, 0.11297526],
       [0.00977181, 0.97065769]])

In [8]:
np.random.rand(3)

array([0.87193428, 0.12092314, 0.66840032])

In [42]:
np.random.randint(4,9) # print random int type number

5

In [43]:
np.random.randint(0,10)

6

In [9]:
np.random.randint(0,10,4)

array([2, 2, 3, 6])

In [10]:
n=np.random.randint(10,40,(8,10)) # fast are generate the random number and the second one is colom and row

In [52]:
n

array([[22, 38, 12, 37, 21, 30, 28, 19, 17, 10],
       [32, 15, 37, 36, 14, 37, 27, 22, 17, 33],
       [16, 14, 20, 22, 32, 39, 39, 39, 16, 31],
       [27, 23, 15, 38, 15, 12, 20, 11, 24, 17],
       [20, 34, 34, 26, 25, 20, 35, 38, 36, 28],
       [16, 34, 10, 37, 13, 17, 23, 38, 31, 16],
       [14, 24, 36, 23, 19, 30, 36, 28, 33, 19],
       [15, 19, 22, 38, 24, 22, 33, 16, 26, 16]])

In [53]:
n[0]

array([22, 38, 12, 37, 21, 30, 28, 19, 17, 10])

In [54]:
n[0,6]

28

In [55]:
n[::-1]

array([[15, 19, 22, 38, 24, 22, 33, 16, 26, 16],
       [14, 24, 36, 23, 19, 30, 36, 28, 33, 19],
       [16, 34, 10, 37, 13, 17, 23, 38, 31, 16],
       [20, 34, 34, 26, 25, 20, 35, 38, 36, 28],
       [27, 23, 15, 38, 15, 12, 20, 11, 24, 17],
       [16, 14, 20, 22, 32, 39, 39, 39, 16, 31],
       [32, 15, 37, 36, 14, 37, 27, 22, 17, 33],
       [22, 38, 12, 37, 21, 30, 28, 19, 17, 10]])

In [56]:
n[::1]

array([[22, 38, 12, 37, 21, 30, 28, 19, 17, 10],
       [32, 15, 37, 36, 14, 37, 27, 22, 17, 33],
       [16, 14, 20, 22, 32, 39, 39, 39, 16, 31],
       [27, 23, 15, 38, 15, 12, 20, 11, 24, 17],
       [20, 34, 34, 26, 25, 20, 35, 38, 36, 28],
       [16, 34, 10, 37, 13, 17, 23, 38, 31, 16],
       [14, 24, 36, 23, 19, 30, 36, 28, 33, 19],
       [15, 19, 22, 38, 24, 22, 33, 16, 26, 16]])

In [57]:
n[::2]

array([[22, 38, 12, 37, 21, 30, 28, 19, 17, 10],
       [16, 14, 20, 22, 32, 39, 39, 39, 16, 31],
       [20, 34, 34, 26, 25, 20, 35, 38, 36, 28],
       [14, 24, 36, 23, 19, 30, 36, 28, 33, 19]])

In [58]:
n[0]

array([22, 38, 12, 37, 21, 30, 28, 19, 17, 10])

In [59]:
n[0,5]

30

In [60]:
n[5,-3]

38

In [61]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Indexing

In [3]:
mat = np.arange(0,100).reshape(10,10)

In [4]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
row=4
col=5

In [6]:
row

4

In [7]:
col

5

In [8]:
mat[row,col]

45

In [9]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [10]:
mat[7]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [11]:
mat[:,col] # with slices
# how to print coloum infor

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [12]:
mat[col]# how to print row

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [13]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [14]:
row

4

In [15]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [18]:
mat[col:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [21]:
mat[1:2,2:4]

array([[12, 13]])

In [22]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

# python program to generat otp 

In [24]:
import random

def generate_otp(length=6):
    """Generate a numeric OTP of a specified length."""
    digits = '0123456789'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 6  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 027399


In [25]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [26]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [27]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000024D37FDC380>


In [28]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
